"""init

Revision ID: ca478a782903
Revises: 
Create Date: 2020-07-31 21:17:54.013757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca478a782903'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document', sa.String(256), nullable=False),
    sa.Column('name', sa.String(256), nullable=False),
    sa.Column('last_name', sa.String(256), nullable=False),
    sa.Column('email', sa.String(256), nullable=False),
    sa.Column('password', sa.String(256), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Boolean(True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_mail'))
    )
    op.create_table('wallets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('_hex', sa.String(256), nullable=False),
    sa.Column('wif', sa.String(256), nullable=False),
    sa.Column('wifc', sa.String(256), nullable=False),
    sa.Column('pubkey', sa.String(256), nullable=False),
    sa.Column('pubkeyc', sa.String(256), nullable=False),
    sa.Column('pubaddr1', sa.String(256), nullable=False),
    sa.Column('pubaddr3', sa.String(256), nullable=False),
    sa.Column('pubaddrbc1_p2wsh', sa.String(256), nullable=False),
    sa.Column('pubaddrbc1_p2wpkh', sa.String(256), nullable=False),
    sa.Column('balances', sa.Float(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Boolean(True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_wallets_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wallets')),
    sa.UniqueConstraint('_hex', name=op.f('uq_wallets__hex')),
    sa.UniqueConstraint('pubaddr1', name=op.f('uq_wallets_pubaddr1')),
    sa.UniqueConstraint('pubaddr3', name=op.f('uq_wallets_pubaddr3')),
    sa.UniqueConstraint('pubaddrbc1_p2wpkh', name=op.f('uq_wallets_pubaddrbc1_p2wpkh')),
    sa.UniqueConstraint('pubaddrbc1_p2wsh', name=op.f('uq_wallets_pubaddrbc1_p2wsh')),
    sa.UniqueConstraint('pubkey', name=op.f('uq_wallets_pubkey')),
    sa.UniqueConstraint('pubkeyc', name=op.f('uq_wallets_pubkeyc')),
    sa.UniqueConstraint('wif', name=op.f('uq_wallets_wif')),
    sa.UniqueConstraint('wifc', name=op.f('uq_wallets_wifc'))
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('origin_address', sa.String(256), nullable=False),
    sa.Column('destination_address', sa.String(256), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('fee', sa.Float(), nullable=False),
    sa.Column('fee_percentil', sa.Float(), nullable=False),
    sa.Column('wallet_id', sa.Integer(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('confirmation_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], name=op.f('fk_transactions_wallet_id_wallets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transactions'))
    )
    # ### end Alembic commands ###

def downgrade():
    pass
